### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by ghost** [jsdocs/jsdocs#19]
I can probably start doing something here in a close future, is this still an active idea?

**Comment by h2non** [comment]
Yes, it is. I'm quite busy lately, but if someone helps me to move forward with the project, I don't mind at all prioritising this project over other personal projects.

Implementing an nice UI is a very nice-to-have here. I would love to have something similar to this:
https://www.mapbox.com/mapbox-gl-js/api/

Also, everything is open to debate and prone to change. For instance, if we want to use another CSS processor, it's totally fine to change it if makes more sense.

**Comment by ghost** [comment]
Alright! I could handle the project in my free time very soon. I do plan to do the redesign and perhaps work on the back-end too. Don't worry if you can't work on it, I'd just need general direction (some kind of outline document would be nice) and I can do the work!

I'm just about to finish the latest version of Concise and it will use a custom processor built on top of Sass and some PostCSS plugins that I wrote, so yeah, that would be a change, but there is no risk since Concise will be commercially supported after this version.

Let me know what you think!

**Comment by h2non** [comment]
Everything looks good to me. Regarding to the project direction, just think about as a easy, intuitive way to browse API docs for JS projects. We can take inspiration from multiple sources, but the link 8 shared before it pretty representrative of what I would like to have.

Feel free to post her the questions you may have and I'll try my best answering them for you.

**Comment by ghost** [comment]
Okay, I'm with stuff at this moment, but I'll certainly be on this soon. Thanks!

**Comment by ghost** [comment]
Okay, I'm ready to continue with this today, I just updated to the latest version of Concise and I'll start building the new front-end.

**Comment by h2non** [comment]
Great!
