### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by ghost** [jsdocs/jsdocs#20]
@h2non I made this for the organization of jsdocs, I'm unable to access to the settings so could you upload it for me? Thanks

![icon](https://cloud.githubusercontent.com/assets/2559808/18734316/9c9d78be-8030-11e6-9081-b699aedc948d.png)

**Comment by tomas-fp** [comment]
Will do tonight!

**Comment by ghost** [comment]
Thanks! I was afraid that you didn't like it; I'm conscious of my unusual type of design. But I'm glad you will do it, thanks.

**Comment by h2non** [comment]
Done! Due to Github CDN cache, it may take a couple of minutes to update the image.

**Comment by ghost** [comment]
Awesome, thanks!
